spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://guico.icu:3306/omg_helper
    username: remoteuser
    password: 411326li?
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.guico.omghelper.domain
  configuration:
    map-underscore-to-camel-case: true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.guico.omghelper.domain
